---
author_association: OWNER
created_at: '2022-05-09T07:41:16Z'
html_url: https://github.com/himanoa/times-himanoa/issues/4#issuecomment-1120754262
id: 1120754262
issue_url: https://api.github.com/repos/himanoa/times-himanoa/issues/4
node_id: IC_kwDOHTMZ985CzVpW
performed_via_github_app: 
reactions:
  "+1": 0
  "-1": 0
  confused: 0
  eyes: 0
  heart: 0
  hooray: 0
  laugh: 0
  rocket: 0
  total_count: 0
  url: https://api.github.com/repos/himanoa/times-himanoa/issues/comments/1120754262/reactions
updated_at: '2022-05-09T07:41:16Z'
url: https://api.github.com/repos/himanoa/times-himanoa/issues/comments/1120754262
user:
  avatar_url: https://avatars.githubusercontent.com/u/18651963?v=4
  events_url: https://api.github.com/users/himanoa/events{/privacy}
  followers_url: https://api.github.com/users/himanoa/followers
  following_url: https://api.github.com/users/himanoa/following{/other_user}
  gists_url: https://api.github.com/users/himanoa/gists{/gist_id}
  gravatar_id: ''
  html_url: https://github.com/himanoa
  id: 18651963
  login: himanoa
  node_id: MDQ6VXNlcjE4NjUxOTYz
  organizations_url: https://api.github.com/users/himanoa/orgs
  received_events_url: https://api.github.com/users/himanoa/received_events
  repos_url: https://api.github.com/users/himanoa/repos
  site_admin: false
  starred_url: https://api.github.com/users/himanoa/starred{/owner}{/repo}
  subscriptions_url: https://api.github.com/users/himanoa/subscriptions
  type: User
  url: https://api.github.com/users/himanoa

---
## TSとResult型

[ts-results](https://github.com/vultix/ts-results) みたいな概念を使用してフロントエンドのコードを書いている時に、ハンドリングしてもどうしようもない `throw new Error("")`  の扱いにかなり困っていた。

これらをハンドリングしても結局なんもできないがUIスレッドを止めたくないので、せめてts-resultsの型で返してほしい みたいなことがそれなりにある。

この問題を解決するために僕は いままで次のようなコードを毎回書いていた。

```typescript
type UserError = { kind: 'notFound' } | { kind: 'unknownError', e: unknown}

const fetchUserProfile = async (id: UserId): Promise<Result<User, UserError>> => {
  try {
    ....
  } catch(e) }
   return Err({kind: 'unknownError', e});
  }
}
```

が、毎回 `try-catch` で囲むのも面倒なので `unsafe(() => { 例外をthrowしうる君})` みたいな感じでラップできるようにするのを作るといいかもなって思った